### ISSUE TITLE
Date locale data structure

### ISSUE THREAD

**Issue by guoyunhe** [ashmaroli/jekyll-locale#17]
Thanks for making this plugin!

I saw the date localization use the following format:

```yaml
date:
  day_names:
    - Sunday
    - Monday
    - Tuesday
    - ...
```
But online translation systems don't support arrays. It would be better to have the following data structure supported:

```yaml
date:
  day_names:
    sun: Sunday
    mon: Monday
    tue: Tuesday
    ...
```
