### ISSUE TITLE
Nested YAML keys cannot be accessed

### ISSUE THREAD

**Issue by guoyunhe** [ashmaroli/jekyll-locale#18]
Using the released version from ruby gem.

I have some nested keys to scope some strings:

```yaml
welcom: Welcom
site:
  title: My Site
```

But when I access the string from locale object:

```
{{ locale.welcome }} // Good
{{ locale.site.title}} // Empty/Undefined
```
